// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['main']['App']['BeforeClose'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function FsExists(arg1, arg2) {
  return window['go']['main']['App']['FsExists'](arg1, arg2);
}

export function GetAvailablePort() {
  return window['go']['main']['App']['GetAvailablePort']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function Hash(arg1) {
  return window['go']['main']['App']['Hash'](arg1);
}

export function InitProjects() {
  return window['go']['main']['App']['InitProjects']();
}

export function ModelStorageDirectory(arg1) {
  return window['go']['main']['App']['ModelStorageDirectory'](arg1);
}

export function ModifyProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModifyProject'](arg1, arg2, arg3);
}

export function OpenStorageDir() {
  return window['go']['main']['App']['OpenStorageDir']();
}

export function PortAvailable(arg1) {
  return window['go']['main']['App']['PortAvailable'](arg1);
}

export function ProjectDBPath(arg1) {
  return window['go']['main']['App']['ProjectDBPath'](arg1);
}

export function ReindexProject(arg1) {
  return window['go']['main']['App']['ReindexProject'](arg1);
}

export function SelectDirDialog(arg1) {
  return window['go']['main']['App']['SelectDirDialog'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StopIndexing(arg1) {
  return window['go']['main']['App']['StopIndexing'](arg1);
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}
