// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function DownloadModel(arg1:string):Promise<string>;

export function GetModels():Promise<Array<backend.Model>>;

export function Startup(arg1:context.Context):Promise<void>;
