// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DownloadModel(arg1:string):Promise<string>;

export function GetModels():Promise<Array<backend.Model>>;

export function GetProjects():Promise<Array<backend.Project>>;

export function ModifyProject(arg1:string,arg2:string,arg3:any):Promise<number>;
