// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}
